name: Deploy to registry (Production)

on:
  push:
    branches: ["main"]

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t dt-app:latest .

      - name: Tag Docker image for registry
        run: docker tag dt-app:latest aroma-images.registry.twcstorage.ru/dt-app:latest

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: aroma-images.registry.twcstorage.ru
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: docker push aroma-images.registry.twcstorage.ru/dt-app:latest
